###
GET http://localhost:9000/moneda HTTP/1.1

###
POST http://localhost:9000/moneda HTTP/1.1
Content-Type: application/json

{
    "codigo_iso": "AUD",
    "nombre": "Dolar Australiano"
}

###
DELETE http://localhost:9000/moneda/9 HTTP/1.1

###
GET http://localhost:9000/tasa_de_cambio HTTP/1.1

###
POST http://localhost:9000/tasa_de_cambio HTTP/1.1
Content-Type: application/json

{
    "moneda_origen": 8 ,
    "moneda_destino": 8,
    "tasa_cambio": 1
}